services:
  - type: web
    name: portfolio-server
    env: node
    plan: free
    buildCommand: cd server && npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 # or leave empty
    autoDeploy: true
